import { writeFileSync, readFileSync, mkdirSync, existsSync } from "fs";
import path from "path";
import { ethers } from "hardhat";

const ADDR_PATH = path.join(process.cwd(), "contracts", "addresses.json");
const FE_PATH = path.join(process.cwd(), "..", "site", "src", "config", "contracts.ts");

function updateAddresses(chainId: string, name: string, addr: string) {
  let db: any = {};
  if (existsSync(ADDR_PATH)) {
    db = JSON.parse(readFileSync(ADDR_PATH, "utf8"));
  }
  if (!db[chainId]) db[chainId] = {};
  db[chainId][name] = addr;
  mkdirSync(path.dirname(ADDR_PATH), { recursive: true });
  writeFileSync(ADDR_PATH, JSON.stringify(db, null, 2));
  return db;
}

function writeFrontendConfig(db: any) {
  const ts = `// auto-generated by deploy script. DO NOT EDIT.
export const CONTRACTS: Record<string, Record<string,string>> = ${JSON.stringify(db, null, 2)} as const;
export const BLIND_ESCROW_ADDR = CONTRACTS["11155111"]?.BlindEscrow ?? "";
export const MOCK_USDC_ADDR    = CONTRACTS["11155111"]?.MockUSDC ?? "";
export const MOCK_DAI_ADDR     = CONTRACTS["11155111"]?.MockDAI ?? "";
`;
  mkdirSync(path.dirname(FE_PATH), { recursive: true });
  writeFileSync(FE_PATH, ts);
}

async function main() {
  console.log("🚀 Starting BlindEscrow deployment only...");
  
  const [deployer] = await ethers.getSigners();
  const network = await ethers.provider.getNetwork();
  const chainId = String(network.chainId);
  
  console.log(`Deployer: ${deployer.address}`);
  console.log(`Network: ${network.name} (${chainId})`);

  // Deploy BlindEscrow only
  console.log("📦 Deploying BlindEscrow...");
  const Escrow = await ethers.getContractFactory("BlindEscrow");
  const escrow = await Escrow.deploy();
  await escrow.waitForDeployment();
  const escrowAddr = await escrow.getAddress();
  console.log(`✅ BlindEscrow deployed at: ${escrowAddr}`);

  // Update addresses.json (keep existing Mock tokens)
  console.log("📝 Updating addresses...");
  let db: any = {};
  if (existsSync(ADDR_PATH)) {
    db = JSON.parse(readFileSync(ADDR_PATH, "utf8"));
  }
  if (!db[chainId]) db[chainId] = {};
  
  // Keep existing Mock tokens if they exist
  const existingMockUSDC = db[chainId]?.MockUSDC;
  const existingMockDAI = db[chainId]?.MockDAI;
  
  // Update only BlindEscrow
  db = updateAddresses(chainId, "BlindEscrow", escrowAddr);
  
  // Restore existing Mock tokens
  if (existingMockUSDC) {
    db[chainId].MockUSDC = existingMockUSDC;
    console.log(`📝 Keeping existing MockUSDC: ${existingMockUSDC}`);
  }
  if (existingMockDAI) {
    db[chainId].MockDAI = existingMockDAI;
    console.log(`📝 Keeping existing MockDAI: ${existingMockDAI}`);
  }

  // Generate frontend config.ts
  writeFrontendConfig(db);

  console.log("✅ Addresses written to:", ADDR_PATH);
  console.log("✅ Frontend config updated:", FE_PATH);
  
  console.log("\n🎉 BlindEscrow deployment completed successfully!");
  console.log("📋 Summary:");
  console.log(`   • BlindEscrow: ${escrowAddr}`);
  if (existingMockUSDC) console.log(`   • MockUSDC: ${existingMockUSDC} (existing)`);
  if (existingMockDAI) console.log(`   • MockDAI: ${existingMockDAI} (existing)`);
  
  console.log("\n🚀 Next steps:");
  console.log("   1. Restart frontend to pick up new BlindEscrow address");
  console.log("   2. Test the complete workflow");
}

main().catch((e) => { 
  console.error("❌ Deployment failed:", e); 
  process.exit(1); 
});
