// auto-generated by deploy script. DO NOT EDIT.
export const CONTRACTS: Record<string, Record<string,string>> = {
  "11155111": {
    "BlindEscrow": "0xb5f2e7cec498327574cD6b8B1456a5f6411Ee46B",
    "MockUSDC": "0xf0Feb273800D5b5Ad6bf5C2c1c6470B0D9bc2C47",
    "MockDAI": "0x8F836a8BaD0cCa454EE150a8F643B4781B6229f6"
  }
} as const;
export const BLIND_ESCROW_ADDR = CONTRACTS["11155111"]?.BlindEscrow ?? "";
export const MOCK_USDC_ADDR    = CONTRACTS["11155111"]?.MockUSDC ?? "";
export const MOCK_DAI_ADDR     = CONTRACTS["11155111"]?.MockDAI ?? "";
