// auto-generated by deploy script. DO NOT EDIT.
export const CONTRACTS: Record<string, Record<string,string>> = {
  "11155111": {
    "BlindEscrow": "0x1234BdE9E93713Dd94f821cF67f56E811131b31C",
    "MockUSDC": "0x8e556C8C89dD97D0Cd114b4bD4D354e80488247D",
    "MockDAI": "0xDe63Cfa0b7d0e52a5eD1975857F7c61858F66aEF"
  }
} as const;
export const BLIND_ESCROW_ADDR = CONTRACTS["11155111"]?.BlindEscrow ?? "";
export const MOCK_USDC_ADDR    = CONTRACTS["11155111"]?.MockUSDC ?? "";
export const MOCK_DAI_ADDR     = CONTRACTS["11155111"]?.MockDAI ?? "";
