// auto-generated by deploy script. DO NOT EDIT.
export const CONTRACTS: Record<string, Record<string,string>> = {
  "11155111": {
    "BlindEscrow": "0x64763CCc67549FbC83cc7CD59B67965a1fB8DBDe",
    "MockUSDC": "0x4954c87dC09a479e33561C4E5537296701Ef1733",
    "MockDAI": "0xB0c41a92641f64a3c804CDD1c779cec17a253681"
  }
} as const;
export const BLIND_ESCROW_ADDR = CONTRACTS["11155111"]?.BlindEscrow ?? "";
export const MOCK_USDC_ADDR    = CONTRACTS["11155111"]?.MockUSDC ?? "";
export const MOCK_DAI_ADDR     = CONTRACTS["11155111"]?.MockDAI ?? "";
